name: check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [gcc12, clang16]
        feature: ['', asan, tsan, ubsan]

    steps:
    - uses: actions/checkout@v3

    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-test-${{ matrix.toolchain }}-${{ matrix.feature }}

    - name: install libtinfo5
      # clang tools link against this
      run: sudo apt-get install -y libtinfo5

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          test \
          --config=${{ matrix.toolchain }} \
          --features=${{ matrix.feature }} \
          //...

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flag:
          - '--config=clang-format'
          - '--config=clang-tidy'
          - '--config=verbose-clang-tidy'
          - '--compilation_mode=opt'
        exclude:
          - flag: ${{ github.event_name == 'pull_request' && '--config=verbose-clang-tidy' || 'dummy' }}

    steps:
    - uses: actions/checkout@v3

    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-build-${{ matrix.flag }}

    - name: install libtinfo5
      # clang tools link against this
      run: sudo apt-get install -y libtinfo5

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          build \
          ${{ matrix.flag }} \
          //...


  buildifier:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-buildifier

    - run: |
        bazel \
          --bazelrc=.github/workflows/ci.bazelrc \
          run \
          //:buildifier.check
